Scraper
P-Programist/pprogramistbot pull request #2
Opened 2021-08-27 04:23 UTC by Reyzhehal

2021-08-29 22:07 UTC, P-Programist requested changes

2021-08-29 22:07 UTC, P-Programist commented on scrapers/job_kg_parser.py
> +            for i in get_all:
for i in ... -> конечно удобно, но пожалуйста используйте более осмысленные перменные

2021-08-29 22:07 UTC, P-Programist commented on scrapers/job_kg_parser.py
> +            company_names = []
Зачем так много листов?
В такой ситуации пробуйте использовать List Comprehension

Нужно разделить этот метод на 4 более маленьких метода:
1.get_descriptions
2.get_company_names
3.get_experiences
4.get_schedules

2021-08-29 22:07 UTC, P-Programist commented on scrapers/job_kg_parser.py
> +        from database.models import (
Импортация внутри метода считается плохой манерой, поэтому перенесите импорты в самый верх

2021-08-29 22:07 UTC, P-Programist commented on scrapers/job_kg_parser.py
> +    async def fillng_database(self):
Относится ли по тематике метод filling_database к этому классу?
Как минимум думаю стоит его вынести из класса и просто передавать данные в метод через параметр функции.
Как максимум создать одну функцию которая примимает любые данные и способна залить это в любою модель.

2021-08-29 22:07 UTC, P-Programist commented on scrapers/job_kg_parser.py
> +        async with AsyncSession(engine, expire_on_commit=False) as session:
Попробуйте сделать этот участок кода в subfunctions или присмотритесь, нет ли там аналога вашей функции.
Постарайтесь без велосипедов если получится, если нет тогда конечно пишите

2021-08-29 22:08 UTC, P-Programist commented
Неплохая работа!

2021-09-03 09:01 UTC, Reyzhehal commented
I created bishkek_vacancy

2021-09-06 05:30 UTC, merged